# .slather.yml

# Coveralls.io is currently supported only through Travis CI and Circle CI, which is not free for demo.

coverage_service: coveralls
workspace: UIPasteboard.xcworkspace
scheme: UIPasteboard
configuration: Debug
source_directory: .
output_directory: ./xml_report
ignore:
  - UIPasteboardTests/*
  - UIPasteboardUITests/*
  - Pods/*
