# .slather.yml

coverage_service: cobertura_xml
workspace: UIPasteboard.xcworkspace
scheme: UIPasteboard
configuration: Debug
source_directory: .
output_directory: ./xml_report
ignore:
  - UIPasteboardTests/*
  - UIPasteboardUITests/*
  - Pods/*
